POST localhost:8080/pet
Content-Type: application/json
X-Token-Id: 5e6b233f-6dd9-4eb9-95f3-f4ca30568825

{
  "id": 0,
  "category": {
    "id": 0,
    "name": "dog"
  },
  "name": "doggie3",
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "sold"
}

####

GET localhost:8080/pet/findByStatus?status=sold
X-Token-Id: 5e6b233f-6dd9-4eb9-95f3-f4ca30568825

###

GET localhost:8080/pet/1

###

POST localhost:8080/pet/1?name=asdasd&status=available


####