POST localhost:8080/user/createWithList
Content-Type: application/json

[
  {
    "id": 0,
    "username": "111",
    "firstName": "111",
    "lastName": "111",
    "email": "111",
    "password": "111",
    "phone": "111",
    "userStatus": 0
  },
  {
    "id": 0,
    "username": "222",
    "firstName": "222",
    "lastName": "222",
    "email": "222",
    "password": "222",
    "phone": "222",
    "userStatus": 0
  },
  {
    "id": 0,
    "username": "333",
    "firstName": "333",
    "lastName": "333",
    "email": "333",
    "password": "333",
    "phone": "333",
    "userStatus": 0
  }
]

###

GET localhost:8080/user/vitya

###

PUT localhost:8080/user/111
Content-Type: application/json

{
  "id": 0,
  "username": "vitya",
  "firstName": "vitya",
  "lastName": "vitya",
  "email": "vitya",
  "password": "vitya",
  "phone": "vitya",
  "userStatus": 0
}

###

DELETE localhost:8080/user/vitya

###

GET localhost:8080/user/login?username=333&password=333
#X-Expires-After: qweqweqw

###

GET localhost:8080/user/logout
X-Token-Id: a8524d69-1ea9-432c-9b05-29cd74c48ebf